[project]
name = "svd-data-compression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mardhav-2008", email = "mardhavrayapati81@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.6",
    "scipy>=1.18.1",
    "soundfile>=0.14.0",
]

[project.scripts]
svd-data-compression = "svd_data_compression:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
