[project]
name = "svd-data-compression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mardhav-2008", email = "mardhavrayapati81@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
svd-data-compression = "svd_data_compression:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
